services:
  monitoring:
    # Container Configuration
    image: checkmk/check-mk-raw:2.4.0-latest  					 # Official Checkmk RAW image
    container_name: checkmk                  		 				 # Explicit container name
    restart: unless-stopped                  						 # Auto-restart unless manually stopped

    # Port Mappings 
    ports:
      - "8000:8000"    												           # Web UI (HTTP)
      - "5000:5000"    												           # Livestatus API (agent communication)
      - "162:162/udp"  												           # SNMP trap receiver (UDP)

    # Environment Variables 
    environment:
      - TZ=Africa/Lagos   											          # Container timezone
      - CMK_PASSWORD=${CMK_PASSWORD:?Password not set}  	# Admin password (mandatory)
      - CMK_SITE_ID=${CMK_SITE_ID:-cmk}      						  # Site ID (default: 'cmk')

    # Storage & Performance
    tmpfs:  														                  # In-memory tmpfs for better performance
      - /opt/omd/sites/cmk/tmp:uid=1000,gid=1000  				# OMD temp directory with permissions

    volumes:
      - /etc/localtime:/etc/localtime:ro    							# Sync host timezone (read-only)
      - data:/omd/sites:rw                  							# Persistent site data storage

volumes:
  data:  															                    # Named volume for Checkmk site data
    driver: local  													              # Stores data on host filesystem
